// Code generated by "stringer -type=Status -trimprefix=Status"; DO NOT EDIT.

package judge

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusAccept-0]
	_ = x[StatusCompilationFailed-1]
	_ = x[StatusRuntimeError-2]
	_ = x[StatusSourceSizeLimit-3]
	_ = x[StatusTimeLimit-4]
	_ = x[StatusMemoryLimit-5]
	_ = x[StatusWrongAnswer-6]
	_ = x[StatusCheckerFailed-7]
	_ = x[StatusJudgeFailed-8]
}

const _Status_name = "AcceptCompilationFailedRuntimeErrorSourceSizeLimitTimeLimitMemoryLimitWrongAnswerCheckerFailedJudgeFailed"

var _Status_index = [...]uint8{0, 6, 23, 35, 50, 59, 70, 81, 94, 105}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
