CREATE TABLE Task (
	id			INTEGER AUTO_INCREMENT PRIMARY KEY,
	owner_name	VARCHAR(40) NOT NULL REFERENCES User(name) ON UPDATE CASCADE ON DELETE SET NULL,
	title		VARCHAR(40) NOT NULL,
	info 		TEXT NOT NULL,
	problem 	BLOB NOT NULL
);