CREATE TABLE Task (
	id			INTEGER AUTO_INCREMENT PRIMARY KEY,
	owner_name	VARCHAR(40),
	title		VARCHAR(40) NOT NULL,
	info 		TEXT NOT NULL,
	problem 	BLOB NOT NULL,
	FOREIGN KEY (owner_name) REFERENCES User(name)
	ON UPDATE CASCADE
	ON DELETE SET NULL
) ENGINE=INNODB;