CREATE TABLE Submission (
	id			INTEGER AUTO_INCREMENT PRIMARY KEY,
	owner_name	VARCHAR(40) NOT NULL REFERENCES User(name) ON UPDATE CASCADE ON DELETE CASCADE,
	task_id		INTEGER NOT NULL REFERENCES Task(id) ON UPDATE CASCADE ON DELETE SET NULL,
	timestamp 	TIMESTAMP NOT NULL,
	score		NUMERIC NOT NULL,
	solution	TEXT NOT NULL
);