CREATE TABLE Submission (
	id			INTEGER AUTO_INCREMENT PRIMARY KEY,
	owner_name	VARCHAR(40) NOT NULL REFERENCES User(name) ON UPDATE CASCADE ON DELETE CASCADE,
	task_id		INTEGER NOT NULL REFERENCES Task(id) ON UPDATE CASCADE ON DELETE SET NULL,
	timestamp 	TIMESTAMP NOT NULL,
	verdict 	INT NOT NULL,
	comment 	TEXT NOT NULL,
	solution	TEXT NOT NULL,
	score		DECIMAL(6,5) NOT NULL
);