CREATE TABLE Submission (
	id			INTEGER AUTO_INCREMENT PRIMARY KEY,
	owner_name	VARCHAR(40) NOT NULL,
	task_id		INTEGER,
	timestamp 	TIMESTAMP NOT NULL,
	verdict 	INT NOT NULL,
	comment 	TEXT NOT NULL,
	solution	TEXT NOT NULL,
	score		DECIMAL(6,5) NOT NULL,
	FOREIGN KEY (owner_name) REFERENCES User(name) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (task_id) REFERENCES Task(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=INNODB;