CREATE TABLE Status (
	owner_name	VARCHAR(40) NOT NULL REFERENCES User(name) ON UPDATE CASCADE ON DELETE CASCADE,
	task_id		INTEGER NOT NULL REFERENCES Task(id) ON UPDATE CASCADE ON DELETE CASCADE,
	score		NUMERIC NOT NULL,
	PRIMARY KEY(owner_name,task_id)
);