CREATE TABLE Status (
	owner_name	VARCHAR(40) NOT NULL,
	task_id		INTEGER NOT NULL,
	score		NUMERIC NOT NULL,
	PRIMARY KEY(owner_name,task_id),
	FOREIGN KEY (owner_name) REFERENCES User(name) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (task_id) REFERENCES Task(id) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=INNODB;